### ISSUE TITLE
Magpie migration to 0.7.0

### ISSUE THREAD

**Issue by davidcaron** [Ouranosinc/Magpie#115]
When migrating to 0.7.0, the `resource_display_name` is added. 

For existing resources in the `resources` table that don't have an empty `resource_display_name` field, the `resource_name` is displayed. We should display the one from the `remote_resources` table when this happens It's not a big change, the comparison is already made to check if the resource exists on the remote server. 

We _could_ persist this `resource_display_name` in the `resources` table in another migration, but I think it's a bit overkill.

**Comment by dbyrns** [comment]
Not sure to fully understand that... the `resources` table already has a `resource_display_name` field? But the value should not be persisted since it came from `remote_resources` If its the case why in the first place the `resources` table should have a `resource_display_name` field?

**Comment by davidcaron** [comment]
Here is an example:

In resources table:
![image](https://user-images.githubusercontent.com/16667564/46686821-4e74ad80-cbc7-11e8-812e-b7f2e8750de8.png)
In remote_resources table:
![image](https://user-images.githubusercontent.com/16667564/46686854-63514100-cbc7-11e8-85c8-e07ab2a230f9.png)
The `resource_display_name` is absent from the `resources` table because the row was created before we were fetching data from the remote server. The DB migration created the empty `resource_display_name` column.
If the row was created from the `remote_resources` table we wouldn't have this issue, and the `resource_display_name` would contain the right information.
