### ISSUE TITLE
Static files are not served properly behind nginx

### ISSUE THREAD

**Issue by davidcaron** [Ouranosinc/Magpie#153]
When magpie is behind an nginx reverse proxy served at an url like: 
https://192.168.99.201/magpie/
In the ui, an example request for an asset looks like:
https://192.168.99.201/static/magpie.png

So it should be:
https://192.168.99.201/magpie/static/magpie.png

I think this should be modified in magpie, and not in nginx, because redirecting /static to /magpie/static could be in conflict with another service relying on the /static route.

**Comment by dbyrns** [comment]
I agree, usually server has a config to specified its hosting root

**Comment by fmigneault** [comment]
Correct me if I'm wrong, but all static routes are fetched and resolved by the pyramid `config.add_static_view` and `request.static_url` methods.
So they don't even go through the server, they stay within the WSGI app running under gunicorn.

And the URL you mention is behaving exactly like proposed: 
https://colibri.crim.ca/magpie/static/magpie.png
