### ISSUE TITLE
adapter: magpieservice: not able to read the config  twitcher.ows_proxy_ssl_verify

### ISSUE THREAD

**Issue by tlvu** [Ouranosinc/Magpie#186]
This is breaking support of self-signed SSL certificate for PAVICS.

twitcher custom.cfg config:
(volume mount to `/opt/birdhouse/src/twitcher/custom.cfg` in docker image `pavics/twitcher:pavics-0.3.16`)
```
[settings]
rpcinterface = false
wps = false
wps-restapi = true
ows-proxy-ssl-verify = false
ows-proxy-protected-path = /ows/proxy
```

twitcher logs:
(`docker exec twitcher bash -c "tail -f /opt/birdhouse/var/log/supervisor/twitcher.log"`)
```
2019-05-27 17:29:43,236 ERROR [TWITCHER][MainThread] ===========debug start =================
2019-05-27 17:29:43,237 ERROR [TWITCHER][MainThread] self.twitcher_ssl_verify=True
2019-05-27 17:29:43,237 ERROR [TWITCHER][MainThread] twitcher.ows_proxy_ssl_verify=None
2019-05-27 17:29:43,238 ERROR [TWITCHER][MainThread] twitcher.ows_proxy_protected_path=/ows/proxy
2019-05-27 17:29:43,239 ERROR [TWITCHER][MainThread] ===========debug end =================
/opt/conda/envs/twitcher/lib/python2.7/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
```

Expected that `twitcher.ows_proxy_ssl_verify=false`, like `twitcher.ows_proxy_protected_path=/ows/proxy` but ended up with `twitcher.ows_proxy_ssl_verify=None` in the logs.

See this debug commit message for details https://github.com/Ouranosinc/Magpie/commit/bd1ee34dd9d0b1c3be316ab8fbb5fdd46d79bf45

Note it's a debug commit, do not merge this commit to master.

**Comment by fmigneault** [comment]
@tlvu 
The mapping must be defined in https://github.com/Ouranosinc/twitcher/blob/pavics-0.3.16/templates/twitcher.ini for buildout to create it.

**Comment by tlvu** [comment]
@fmigneault oh thanks !  So I checked on master of twitcher and this settings is still not there in `templates/twitcher.ini`, which means self-signed SSL cert support has never worked properly and still broken in latest twitcher (ouranos version).  I also know our twitcher and upstream birdhouse twitcher differ massively and birdhouse twitcher might have a different implementation of self-signed SSL cert support.  Should I PR this change or you'll do it since you are working on twitcher/magpie right now and you might do it differently?

**Comment by tlvu** [comment]
Oh wait, I keep forgetting, there's another version of ouranos twitcher, the OGC invisible branch that is newer than master branch and that `templates/twitcher.ini` change should be there already.

**Comment by tlvu** [comment]
Sorry, false alarm, self-signed SSL cert support should be working properly on that invisible OGC branch.  Problem on my side when backporting that fix from the OGC branch to my deployment.

@fmigneault just a friendly reminder, if you are releasing a new twitcher/magpie for Ouranos, please include that self-signed SSL cert support from the OGC branch.  Thanks and sorry for the false alarm.

**Comment by fmigneault** [comment]
@tlvu  
In the newer versions, only the  `twitcher.ini` is used (no more cfg files, buildout, etc.)
So only need to define this setting directly in this file to enable it. 
We will need to check if any request need to integrate this option directly in the most recent code base. 
I have tried to backport many things, but the project changed so much that I might have missed such cases.
