### ISSUE TITLE
User names with non-ascii characters block some endpoints

### ISSUE THREAD

**Issue by davidcaron** [Ouranosinc/Magpie#208]
When one user has non-ascii characters in its username, some endpoints don't work:

- adding a new user (I guess this is because there is a unique constraint on the username, so the other usernames are read)
- deleting this user

**Comment by fmigneault** [comment]
Duplicates #171

**Comment by fmigneault** [comment]
Use case should be handled since the introduction of https://github.com/Ouranosinc/Magpie/commit/e493be0d4a6bf6c81b417c5e142a027f48d341c4 in 2.0.0 with `PARAM_REGEX`, checked against #84
