### ISSUE TITLE
Pressing return when editing user password deletes the user completely

### ISSUE THREAD

**Issue by davidcaron** [Ouranosinc/Magpie#209]
When editing the user password and pressing Return, the default browser behavior is to submit the form. But because there is more than one `input type="submit"` on the page, I guess the first one is submitted. The first one happens to be the `Delete` button. So the user is completely deleted. 

![image](https://user-images.githubusercontent.com/16667564/64028952-a84cd180-cb11-11e9-99c8-a9e2895f32bd.png)

**Comment by dbyrns** [comment]
Wow great catch!!
