### ISSUE TITLE
WMS parsing of THREDDS service

### ISSUE THREAD

**Issue by fmigneault** [Ouranosinc/Magpie#234]
Support the new functionality of integrated WMS in Thredds.

**Comment by fmigneault** [comment]
@huard @dbyrns 
Please provide more details about the exact use case, not sure I understood everything.

**Comment by huard** [comment]
THREDDS provides for each file/dataset a list of services: HTTP, Opendap, NCML, UDDC, ISO, WCS, WMS. 

https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/catalog/birdhouse/testdata/flyingpigeon/cmip5/catalog.html?dataset=birdhouse/testdata/flyingpigeon/cmip5/tasmax_Amon_MPI-ESM-MR_rcp45_r2i1p1_200601-200612.nc

A potential use case is for someone to allow anonymous access to the ISO and UDDC services, but private access to all other services.

**Comment by dbyrns** [comment]
Right now, when we access the twitcher/ows/proxy/thredds the read permissions is check to allow access to the /catalog/{resource} /fileServer/{resource} and /dodsC/{resource} sub-services. We need to ensure that every other sub-services which are now active (see https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/catalog/birdhouse/cmip5/NASA-GISS/GISS-E2-R-CC/rcp85/mon/seaIce/r1i1p1/sic/catalog.html?dataset=birdhouse/cmip5/NASA-GISS/GISS-E2-R-CC/rcp85/mon/seaIce/r1i1p1/sic/sic_OImon_GISS-E2-R-CC_rcp85_r1i1p1_207601-210012.nc) iso, wcs, wms can be accessed the same way. 

For now let's use the "read" permission also and @huard will tell us if we need a read_wms, read_wcs, read_opendap, etc. permissions.

**Comment by dbyrns** [comment]
Ok well, @huard beat me with his post, so at least we will require the read_iso and read_uddc permissions for these two services. read could still be used for the others sub-services unless other needs arise.

**Comment by huard** [comment]
I don't know if it's usefult, but I think we could split services into two categories: metadata access and data access. 

Metadata-only access: NCML, ISO, UDDC
Data access: HTTP, Opendap, WCS, WMS

**Comment by dbyrns** [comment]
Very useful.
I propose 3 permissions then write, read_metadat, read_data with the subservices mapping provided by @huard .

**Comment by fmigneault** [comment]
3 permissions for BROWSE metadata and READ/WRITE data are  implemented by #361 via PRs #353 and #363
