### ISSUE TITLE
Creating a new user also creates a new group

### ISSUE THREAD

**Issue by huard** [Ouranosinc/Magpie#24]
Is this the desired behavior ?

**Comment by fderue** [comment]
Yes it is. Each user has its own group (with the same name), so that we manage user's permissions only through group's permission functions.

**Comment by huard** [comment]
The issue I see is that is pollutes the group namespace. What happens if I delete the group and instead assign the "user" group to the new user?

**Comment by dbyrns** [comment]
The user's group allow you to assign specific permissions to a particular user. If this group doesn't exist then the user as no exclusive set of permissions. Deleting a user remove its group but their is no validation on the group itself. We should prevent group removal if users are assign to it and we should forbid adding or removing user to the user specific group. It would solve your issue. Also we could filter the user specific group from the real one from the UI to avoid clutter. And propose permission editing for "user" while still editing their related group under the hood.

In brief all could be done by the UI and some validation in the api.

**Comment by huard** [comment]
Ah, thanks for the clarifications ! Bonne fin de semaine.
