### ISSUE TITLE
Verify Magpie Signout procedure

### ISSUE THREAD

**Issue by fmigneault** [Ouranosinc/Magpie#29]
It seems the Magpie signout is not invaliding properly the logged in user.

This doc: [ziggurat-foundations](http://ziggurat-foundations.readthedocs.io/en/0.6.4/configuration.html?highlight=sqlalchemy#automatic-user-sign-in-sign-out) seem to suggest the `header` must be passed to the HTTPOk response. But it doesn't seem to be the case currently: 

https://github.com/Ouranosinc/Magpie/blob/40d574137c626d7bffe1cd73c7d2537f9c633dde/magpie/login/login.py#L122

References issue [pavics-sdi #33](https://github.com/Ouranosinc/pavics-sdi/issues/33)

**Comment by ldperron** [comment]
Waiting for a magpie release
