### ISSUE TITLE
Informative error message on login failure

### ISSUE THREAD

**Issue by huard** [Ouranosinc/Magpie#30]
At the moment we get 
```
{"reason": "not specified", "code": 401, "type": "application/json", "detail": "Login failure"}
```
I'd like to know whether it is because the user does not exist or the password is wrong, and eventually, an HTML page with a link to make a request to get an account or send a message to obtain the password.

**Comment by tomLandry** [comment]
Security mechanisms best practices will be implemented and integrated in OGC Testbed-14.

**Comment by fmigneault** [comment]
@huard 
Which request was used that made this output? Via Magpie UI or directly with the REST API?

Users can already be fetched with the API, using `<magpie_url>/users`
And specific user details are obtained with `<magpie_url>/users/<user_name>`

Password is obviously omitted for security reasons.

All details about the available requests :  [Magpie REST API ](https://app.swaggerhub.com/apis/fderue/magpie-rest_api)  (ignore the 'error' warning, all displays properly)

**Comment by huard** [comment]
Agreed.
