### ISSUE TITLE
magpie_cli batch_update_users do not honor password field in config.yml file

### ISSUE THREAD

**Issue by tlvu** [Ouranosinc/Magpie#355]
According to https://github.com/Ouranosinc/Magpie/blob/dd6ea98b132cc65d585c9cef0f53a929e30a3059/config/config.yml#L16-L24
if an optional field is specified it should have honored the specified value.  But the password field is not honored.

How to reproduce:

Run the script at https://github.com/bird-house/birdhouse-deploy/blob/707e6afc762e5eae76a19011f83c0eb868500b0b/birdhouse/scripts/create-magpie-users#L1-L40 with the same sample config.yml in the script header comment.

Output: [magpie_create_users_log__20200928__215021.txt](https://github.com/Ouranosinc/Magpie/files/5295379/magpie_create_users_log__20200928__215021.txt) shows password field is not honored.

**Comment by fmigneault** [comment]
The password need to fulfill the requirement of `MAGPIE_PASSWORD_MIN_LENGTH` (default: 12). 
Is the password employed if the length is valid? It will help track down the problem.

**Comment by tlvu** [comment]
> The password need to fulfill the requirement of `MAGPIE_PASSWORD_MIN_LENGTH` (default: 12).
> Is the password employed if the length is valid? It will help track down the problem.

Oh indeed the password was 'bogus' so only 5 char length

Can you document this minimum length requirement in the sample config.yml file and also show warnings or errors somewhere when the tool runs?

**Comment by fmigneault** [comment]
Will add the info in the config. To idea to prevent this issue in advance.
Is there some warning/error logged from the request? I'm surprised the user gets created at all.
The response message is supposed to specifically indicate the cause of invalid length, but maybe its not explicitly logged by the CLI.

**Comment by tlvu** [comment]
Is there another restriction than the minimum 12 password length?  I made it 12 and still not honored.

**Comment by tlvu** [comment]
Full console output below.  This time I made the password 12 in length.

```
$ scripts/create-magpie-users
+ docker run --rm -it --name create_magpie_users -v /tmp/create_magpie_users:/tmp/create_magpie_users:rw pavics/magpie:2.0.0 magpie_cli batch_update_users https://pavics.ouranos.ca/magpie admin 'sanitized' -f /tmp/create_magpie_users/config.yml -o /tmp/create_magpie_users/                          
Constant could not be found: GITHUB_CLIENT_ID (using default: None)                                                                                   
Constant could not be found: GITHUB_CLIENT_SECRET (using default: None)                                                                               
Constant could not be found: WSO2_HOSTNAME (using default: None)                                                                                      
Constant could not be found: WSO2_CLIENT_ID (using default: None)                                                                                     
Constant could not be found: WSO2_CLIENT_SECRET (using default: None)                                                                                 
Constant could not be found: WSO2_CERTIFICATE_FILE (using default: None)                                                                              
Constant could not be found: WSO2_SSL_VERIFY (using default: True)
28-Sep-20 23:15:37 - INFO - Output results sent to [/tmp/create_magpie_users/magpie_create_users_log__20200928__231537.txt]

$ cat /tmp/create_magpie_users/magpie_create_users_log__20200928__231537.txt

USERNAME     PASSWORD         RESULT
____________________________________________________________

bogus01      I1gthT3JgjAb     200 : Login successful.
bogus02      McsksZTe7nwN     200 : Login successful.
bogus03      8a3GKcaqRxFW     200 : Login successful.
```

**Comment by tlvu** [comment]
Oh wait a sec, the magpie server is version `1.7.3` (from PAVICS).  `magpie_cli` is `2.0.0` from the new docker image.  Does that explain why even if I set the password length to 12, it's still not honored?

**Comment by tlvu** [comment]
If the restriction(s) is/are server-side, then please also document from which version the restriction(s) is/are in places.  If there are more than 1 restriction, please document them all and ensure proper errors are logged server-side and if possible send those errors back to client-side for immediate feedback to the user.

**Comment by tlvu** [comment]
Currently for Magpie server-side version `1.7.3` no errors are logged about restrictions not met for the password field.

**Comment by fmigneault** [comment]
> Oh wait a sec, the magpie server is version `1.7.3` (from PAVICS). `magpie_cli` is `2.0.0` from the new docker image. Does that explain why even if I set the password length to 12, it's still not honored?

For remove `1.7.3`, the 12 char limit will not exist, so it should work directly. 
It might be that the `password` parameter is not correctly extracted from the config. 
At least we know its not because <12 char that the value is ignored. 
I will try to dig for the cause.

**Comment by fmigneault** [comment]
> If the restriction(s) is/are server-side, then please also document from which version the restriction(s) is/are in places. If there are more than 1 restriction, please document them all and ensure proper errors are logged server-side and if possible send those errors back to client-side for immediate feedback to the user.

The CLI can only report the errors raised by the API. Magpie `1.7.3` did not have a concept of min password length, so it can't report that. Otherwise you would see the specific message. The combinations of restrictions really depends on whatever the server-version is, so I guess the changelog is the best place to look up. All modifications are detailed there.

If found the password is indeed ignored when provided by config, so I will provide a fix for that.

**Comment by tlvu** [comment]
> The CLI can only report the errors raised by the API. Magpie `1.7.3` did not have a concept of min password length, so it can't report that. Otherwise you would see the specific message. The combinations of restrictions really depends on whatever the server-version is, so I guess the changelog is the best place to look up. All modifications are detailed there.

OK, no need to doc the restrictions in the sample `config.yml` if user receive error message directly via `magpie_cli`.  Thanks.
