### ISSUE TITLE
Separate personal groups from standard groups

### ISSUE THREAD

**Issue by dbyrns** [Ouranosinc/Magpie#37]
magpie/ui/groups : 
- Should not show personal groups (solve also the problem that personal group should not be deleted directly (they are when deleting a user)

magpie/ui/users/add : 
- Combobox "user group" should not show personal groups

magpie/ui/users/username : 
- Groups Membership should not show personal groups (solve also the problem that a user should not be able to remove its own personal group)
- A panel showing personal group permission as in magpie/ui/groups/username/default should be shown (this is a more intuitive way to edit "user" permission. The fact that in the background we handle this by using a personnal group doesn't need to be shown in the UI)

**Comment by fmigneault** [comment]
@dbyrns 
How should we handle following cases:

1. Creation of a new user, the "user group" dropdown list will have which default group, if any?
2. User "admin" is currently used as a joinable group my multiple other users, but is also an actual "user" on itself. Should a new group "administrators" be made for the purpose of joining/allowing admin rights and user "admin" remain a hidden special case?
3. User "anonymous" which is used as "not signed in", but is also a user internally... should it be hidden?

**Comment by dbyrns** [comment]
1. I would say "users" (which means you can use the platform).
2. Good point, I like your solution but will need a thorough reflexion to avoid breaking something upon deployment.
3. No because we need it to allow permission editing.

So a fresh set of users/groups would be:
Users:
anonymous (with the hidden anonymous group)
admin (with the hidden admin group)

Groups:
users (standard permissions to use the platform), no members
administrators (permissions editing authorisation only), admin as member

As new users are created they will be either "users" or "administrators" or both. And some groups could be added as needed but I see a limited number of them without user "group" pollution.

**Comment by fmigneault** [comment]
closed via PR #46
