### ISSUE TITLE
Project Workspaces Support in Magpie

### ISSUE THREAD

**Issue by fmigneault** [Ouranosinc/Magpie#39]
Full Details: [here](https://www.crim.ca/confluence/pages/viewpage.action?pageId=21760512)

- Workspace permissions under ~~`Project`~~ `thredds` service (read, write)
- ~~maybe more granular perms: 
  `CRUD Workflow (4) / CRUD dataset (4) / CRUD workflow (4) / CRUD search criterias (4) / CRUD jobs (4) => 20 + CRUD project => 24 permissions`~~

- ~~New routes:~~ 
  - ~~GET `{host_bird}/magpie/services/project` 
    details about project service~~
  - ~~GET `{host_bird}/magpie/services/project/permissions` 
    possible permissions (read, write, ...)~~
  - ~~GET `{host_bird}/magpie/services/project/resources` 
    list of registered projects~~
  - ~~GET `{host_bird}/magpie/services/project/resources/{id}` 
    details of specific project~~
  - ~~GET `{host_bird}/magpie/services/project/resources/{id}/permissions` 
    specific project permissions~~
  - ~~GET `{host_bird}/magpie/services/project/resources/{id}/user/{id}/permissions` 
    user project permissions (grant other user access to their project and such)~~
  - ~~POST `{host_bird}/magpie/services/project/resources/{name}` 
    create project~~
  - ~~PUT `{host_bird}/magpie/services/project/resources/{id}/permissions` 
    update project permissions~~

- Permissions: 
  - read
  - write
  - (?)

**Comment by fmigneault** [comment]
@dbyrns validation / additions?

**Comment by fmigneault** [comment]
@Renaud009 permissions updates?

**Comment by fmigneault** [comment]
wontfix
geoserver WFS will have projet workspaces Ouranosinc/Magpie#42

**Comment by fmigneault** [comment]
relates to Ouranosinc/Magpie#44

**Comment by Renaud009** [comment]
@dbyrns Le plan c'est de mettre project-api derrière twitcher (A) ou de le laisser ouvert (B)
Si A: On fournit les routes à protéger à twitcher
Si B: Doit créer un hook pour chaque route dans projet-api pour appeler magpie et valider le token et la permission

**Comment by dbyrns** [comment]
@Renaud009 ça dépend de ce que fait project-api.
Si la majorité des routes sont reliées à une ressource/workflow/etc. directement et que l'absence de permission devrait retourner un 403 alors twitcher pourrait faire le travail (Donc A)
Si par contre les routes doivent retourner une réponse (200) avec un contenu filtré selon qui est loggé, donc des routes pas forcément reliées à une ressource/permission alors je crois que B serait plus approprié. 
Je crois que l'on se trouve avec A, mais je te laisse valider.

**Comment by Renaud009** [comment]
Je crois aussi qu'on est dans A), la seule route à filtrer en fonction des permissions à ma connaissance est GetProjects. L'autre chose qui ne marchera pas pour A) c'est si:
- twitcher n'est pas capable de lire un projectId dans un paramètre du GET (stocké dans un  json)
- ou si j'envois parfois le projectId dans le body des requêtes PUT/PATCH ce qui et souvent le cas je crois

Je vous reviens dans tous les cas avec une liste des routes utilisées d'ici quelques minutes

**Comment by dbyrns** [comment]
Pour GetProjects alors twitcher la traitera comme une route public (donc tous le monde passe) et ProjectAPI aura pour responsabilité de faire appel à Magpie dans ce cas là pour filtrer sa réponse.
Le module twitcher pour project-api sera spécialisé comme tous les autres d'ailleurs, donc il peut prendre l'info là où elle est (jeton json, projectid, etc)

**Comment by Renaud009** [comment]
**OPEN access** (project-api will validation token and permission with magpie for such routes
- GET <BIRD>/project-api/api/Projects?*
**following 3 calls do not expose projectId anywhere
- DELETE <BIRD>/project-api/api/Datasets/<DATASETID>
- DELETE <BIRD>/project-api/api/Researchs/<RESEARCHID>
- DELETE <BIRD>/project-api/api/Workflows/<WORKFLOWID>

**READ access**
- GET <BIRD>/project-api/api/Projects/<PROJECTID>/datasets
- GET <BIRD>/project-api/api/Projects/<PROJECTID>/jobs
- GET <BIRD>/project-api/api/Projects/<PROJECTID>/researchs
- GET <BIRD>/project-api/api/Projects/<PROJECTID>/workflows
**following call use a filter param that is a json object urlEncoded() and are equivalents to previous calls**:
- GET <BIRD>/project-api/api/Projects?filter=%7B%22where%22:%7B%id%22:<PROJECTID>%7D%7D
- GET <BIRD>/project-api/api/Datasets?filter=%7B%22where%22:%7B%22projectId%22:<PROJECTID>%7D%7D
- GET <BIRD>/project-api/api/Jobs?filter=%7B%22where%22:%7B%22projectId%22:<PROJECTID>%7D%7D
- GET <BIRD>/project-api/api/Researchs?filter=%7B%22where%22:%7B%22projectId%22:<PROJECTID>%7D%7D
- GET <BIRD>/project-api/api/Workflows?filter=%7B%22where%22:%7B%22projectId%22:<PROJECTID>%7D%7D

**WRITE access**:
PATCH/PUT <BIRD>/project-api/api/Projects/<PROJECTID>?*
**following 3 calls send a projectId on the json body of the request** `{..."projectId":<PROJECTID>...}`
PATCH/PUT/POST <BIRD>/project-api/api/Datasets/<DATASETID>?*
POST <BIRD>/project-api/api/Jobs/<JOBID>?*
POST <BIRD>/project-api/api/Researchs/<RESEARCHID>?*
PATCH/PUT/POST <BIRD>/project-api/api/Workflows/<WORKFLOWID>?*
**following 3 calls do not expose projectId anywhere.... (moved into OPEN access list)
DELETE <BIRD>/project-api/api/Datasets/<DATASETID>
DELETE <BIRD>/project-api/api/Researchs/<RESEARCHID>
DELETE <BIRD>/project-api/api/Workflows/<WORKFLOWID>

**BLOCKED access**:
All others routes should be blocked, please consult http://hirondelle.crim.ca:3005/explorer/
Are you using a white or black urls list?
**I do not seem to call specific project resource  with GET <BIRD>/project-api/api/Datasets/<DATASETID>?, block them for now

**Permission de création d'un projet?!?!?**
POST <BIRD>/project-api/api/Projects?*

**Comment by fmigneault** [comment]
relates to Ouranosinc/PAVICS-project-api#10

**Comment by fmigneault** [comment]
branch https://github.com/Ouranosinc/Magpie/tree/issue-39_project-api-service
basic setup done
@dbyrns @Renaud009 
Something more to add?
Other permissions? (currently read/write)
Is there a need for specific resource types? (currently allowed are file/directory, is that good?)
Additional parameters in request?

Will need following PRs for everything to be deployed:
- Ouranosinc/Magpie/pull/46
- Ouranosinc/Magpie/pull/48
- Ouranosinc/PAVICS/pull/83

**Comment by Renaud009** [comment]
@fmigneault Just notify me when the 3 PRs are deployed. 
Concerning the signin method (or virtually all methods) not supporting JSON body, did you investiguate this?

**Comment by fmigneault** [comment]
@Renaud009 
Which ones specifically did you find that didn't support a JSON?
I can adjust them. I try to make all API requests return at least :
```
{
  "code": <HTTP-code>,
  "type": "application/json",
  "detail": "<message>"
  "reason": "<error reason if applicable>"
}
```

**Comment by fmigneault** [comment]
@Renaud009 for signin: 
https://app.swaggerhub.com/apis/CRIM/magpie-rest_api/0.5.x#/Login/post_signin

**Comment by fmigneault** [comment]
closed via PR #46

**Comment by dbyrns** [comment]
@fmigneault  should we really close this since all the routes above are not fully covered by magpie right now?

**Comment by Renaud009** [comment]
@fmigneault As said previously, signin method with json body has never worked before...
Haven't tested all others methods yet

**Comment by Renaud009** [comment]
The error: {"reason": "Could not retrieve `user_name`.", "code": 400, "type": "application/json", "detail": "Login failure"}
But the same credentials works with application/x-www-form-urlencoded

**Comment by fmigneault** [comment]
indeed doesn't work with application/json, will look into that

**Comment by Renaud009** [comment]
POST https://colibri.crim.ca/magpie/services/project-api/resources
with payload: 
```
{
  "resource_name": 'whatever tried integers too',
  "resource_type": "project-api"
}
```
returns
```
{
    "code": 406,
    "type": "application/json",
    "detail": "Invalid value 'None' specified using key 'resource_name'",
    "param": "None"
}
```

**Comment by Renaud009** [comment]
Pretty sure every routes fail at parsing json body ...

**Comment by Renaud009** [comment]
Based on magpieUI: property "resource_type" of resources should be documented as string accepting only 'file' and 'directory' as value.

**Comment by Renaud009** [comment]
and I cannot find permissions for any service/resources, nor can I add such permissions with the api

**Comment by dbyrns** [comment]
In fact, I think that FX misinterpreted what was actually a JSON payload... @fmigneault is now aware of what we should do.

**Comment by fmigneault** [comment]
@Renaud009 
I run the following call to add a permission, worked

![image](https://user-images.githubusercontent.com/19194484/40813833-dbbef0f2-650a-11e8-8c15-0ecd75cc787c.png)

For fetching allowed permissions of specific service/resources, this is a know issue for now #40

**Comment by Renaud009** [comment]
Is there any tempfix for me to register a new resource? Added query params as suggested by david (application/json body), POST https://colibri.crim.ca/magpie/services/project-api/resources?resource_name=abc&resource_type=file return same error (406), tried x-www-form-url-encoded content-tye with same result...

**Comment by fmigneault** [comment]
@Renaud009 
![image](https://user-images.githubusercontent.com/19194484/40857127-3530846e-65a8-11e8-87e9-4b57b53850e2.png)

`parent_id` is needed

**Comment by dbyrns** [comment]
And to get the parent id (root node in your case) you can get it using "project-api":"resource_id" with the following request:
https://colibri.crim.ca/magpie/services/project-api
`{
"code": 200,
"project-api": {
"resource_id": 148,
"permission_names": [],
"service_name": "project-api",
"public_url": "https://colibri.crim.ca/twitcher/ows/proxy/project-api",
"service_url": "http://colibri.crim.ca:3005/project-api",
"service_type": "project-api"
},
"type": "application/json",
"detail": "Get service successful"
}`

**Comment by Renaud009** [comment]
Please document it with swagger...

**Comment by fmigneault** [comment]
@Renaud009 it is documented in v0.5.0

**Comment by Renaud009** [comment]
Je reçois un erreur 401 sur GET https://colibri.crim.ca/magpie/services/project-api/resources lorsque je fais un appel avec le token d'un utilisateur (ça marche avec un admin). J'ai besoin de cette route pour connaitre la liste de projets auxquels un utilisateur a les accès

Route
`GET https://colibri.crim.ca/magpie/services/project-api/resources`
User (colibri)
`renaud2/renaud2`
Response
```
{
    "request_url": "https://colibri.crim.ca/magpie/services/project-api/resources",
    "code": 401,
    "type": "application/json",
    "route_name": "/services/project-api/resources",
    "detail": "Unauthorized. Insufficient user privileges or missing authentication headers."
}
```

**Comment by dbyrns** [comment]
Toutes les routes magpie sont réservées aux membre admin (administrators dans la version en cours de déploiement). C'est pour cela que tu auras en config un user au nom duquel tu pourras faire les queries voulues.

**Comment by Renaud009** [comment]
Ah ok je pensais utiliser le token admin pour certaines routes mais pas toutes.
Fuck je me suis battu pendant 2 jours pour aller chercher le token du user dans loopback.
Donc je vais privilégier la route GET https://<bird>/magpie/users/<username>/resources
Ah non, je n'ai pas nécessairement perdu mon temps car je dois être certain de la validité du token du user quand même, avec la route /session ou quelque chose du genre

**Comment by dbyrns** [comment]
...et le jour où on boniefera les routes pour être filtrées selon le user tu auras le token.

**Comment by Renaud009** [comment]
Updated routes list to be blocked by twitcher

**Comment by Renaud009** [comment]
The route I want to use (POST magpie/services/project-api/resources) still not work
![image](https://user-images.githubusercontent.com/14914217/41117398-e649b0de-6a5a-11e8-8da9-f0589312e6fc.png)

**Comment by fmigneault** [comment]
see PR #55

**Comment by fmigneault** [comment]
closed via PR #61, deployed on colibri
