### ISSUE TITLE
Geoserver workspace

### ISSUE THREAD

**Issue by huard** [Ouranosinc/Magpie#44]
There is a desire at Ouranos to use Geoserver to store layers that are not directly related to the PAVICS platform (ie results from past projects). It could be done by creating a PAVICS-frontend workspace, and modifying the frontend to have it filter for only the shapefiles within this workspace. Another option is to set up an other independent GeoServer instance, but I'm concerned it would increase the maintenance load. Thoughts ?

**Comment by tomLandry** [comment]
I think several GeoServers (well in general WCS/WFS/WMS servers) is a good approach if we adopt the same registry approach as we do for WPS providers. In the future, we will have to hook up to a variety of servers.

**Comment by Zeitsperre** [comment]
What about creating private/isolated workspaces? This could give specific access to certain files on a user-to-user basis. This functionality became available in GeoServer 2.13.

@huard Are you suggesting creating a different front-end experience? I can see the value in creating a more simplified front-end for non-technical users. I have no idea if more than one front-end can be set up using a single GeoServer, but having a project-specific experience (e.g. ArcticNet) would be a much better option than building a new server, I imagine.

**Comment by huard** [comment]
@Zeitsperre Yes, something like a CKAN catalog would do nicely. And there is no problem hooking up multiple frontends to the same geoserver backend.

**Comment by dbyrns** [comment]
Just so you know we have a short-term goal to add geoserver workspaces support in the frontend (no more public only) with permission based filtering (done on magpie like for thredds). So I think that the workspace approach is easier to make in place and less maintenance heavy like David said.

**Comment by tlogan2000** [comment]
@dbyrns and I discussed this quickly this morning ... and he just commented right now so I will quit typing :)

**Comment by huard** [comment]
Je suis a l'entrée, pouvez vous me faire entrer?

**Comment by fmigneault** [comment]
Geoserver workspaces now supported via `geoserver-api` read/write permissions. (#62, #69)
