### ISSUE TITLE
configs all over the place

### ISSUE THREAD

**Issue by fmigneault** [Ouranosinc/Magpie#45]
Multiple configs (ENV variables, settings, etc.) are either hardcoded in various locations, or default values in case of `getenv` calls fail are defined across multiple files, which makes it hard to track which ones are really used.

All configs should be defined in `magpie.env` file and loaded from there, unless already defined in the host machine.

`Dockerfile` should also retrieve these env variables unless already defined. (some are defined directly in the script currently [at least until 9e25c04])
Maybe also remove ENV specific to `pavics` ? Replace by default values (eg: localhost and such)?

**Comment by fmigneault** [comment]
@dbyrns Could this cause any issue with docker-compose configs afterward loaded? Are ENV already set by pavics-compose ?

**Comment by dbyrns** [comment]
envs are set here in the compose : https://github.com/Ouranosinc/PAVICS/blob/master/birdhouse/docker-compose.yml#L247-L248
Some of the dockerfile env are thus overrided and I agree that they should be defaulted to generic values.
I also agree that a magpie.env could be provided with default values to avoid the getenv with default values all around the place.

**Comment by fmigneault** [comment]
@dbyrns 
Are all .env files automatically loaded by the compose's routine?
Or is there a specific python function that I should execute on Magpie startup to do so?
I'm thinking about the order in which .env files overrides during the docker image creation.
For example to update the db, I need the corresponding credentials of PAVICS, but my understanding is that the .env is not replaced and loaded until the image is pulled and started. So would the image already have the "default" ENV incorrectly set during the build?

**Comment by ldperron** [comment]
With the env_file directive, docker-compose parses the files given in parameter and add a environment variable for every variable found, as if we started the container using the docker "-e" option. If you modify the specified .env file and restart the container using "restart", the change won't be effective. You'll need to recreate the container to make the changes effective (i.e. docker-compose up -d)
