### ISSUE TITLE
[BUG] ncWMS2 unaccessible while it is fully open to anonymous group

### ISSUE THREAD

**Issue by tlvu** [Ouranosinc/Magpie#468]
**Describe the bug**
ncWMS2 service unaccessible while it is fully open to anon group.

This happens after we resume from a power outage, without any config change.  This service has been working fine forever before.

The impact is now the canarie monitoring page (https://pavics.ouranos.ca/canarie/) is not working and we appear down for Canarie.

Error for the canarie monitoring:
```
[2021-09-24 20:49:01 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:1548)
[2021-09-24 20:49:01,632] [1548] [ERROR] app_object : Exception occurs while trying to check status of node.ncWMS2-public
[2021-09-24 20:49:01,632] ERROR in monitoring: Exception occurs while trying to check status of node.ncWMS2-public
[2021-09-24 20:49:01 +0000] [1548] [INFO] Worker exiting (pid: 1548)
```
**To Reproduce**
1. PAVICS https://github.com/bird-house/birdhouse-deploy/tree/1.15.2 (Magpie 3.14.0)
2. ncWMS2 fully open for anon group

![Screenshot 2021-09-24 at 16-58-21 Magpie](https://user-images.githubusercontent.com/11966697/134739079-c438f727-6355-4248-b525-27fc0f446950.png)
![Screenshot 2021-09-24 at 16-54-41 Magpie](https://user-images.githubusercontent.com/11966697/134739002-0ede36cd-b1b3-40c7-b990-1619d1f80c2e.png)

3. But ncWMS2 is in-accessible:
```
$ curl --include https://pavics.ouranos.ca/twitcher/ows/proxy/ncWMS2
HTTP/1.1 400 Bad Request
Server: nginx/1.13.6
Date: Fri, 24 Sep 2021 21:00:29 GMT
Content-Type: text/xml; charset=UTF-8
Content-Length: 597
Connection: keep-alive

<?xml version="1.0" encoding="utf-8"?>
<ExceptionReport version="1.0.0"
    xmlns="http://www.opengis.net/ows/1.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd">
    <Exception exceptionCode="MissingParameterValue" locator="request">
        <ExceptionText>Missing or unknown &#x27;Permission&#x27; inferred from OWS &#x27;request&#x27; parameter: [None]. Unable to resolve the requested access for service: [ncWMS2].</ExceptionText>
    </Exception>
</ExceptionReport>
```

**Comment by fmigneault** [comment]
This error is not inaccessible. It is indicating that `request` query parameter is missing. 
Following works while unauthenticated: 
 https://hirondelle.crim.ca/twitcher/ows/proxy/ncWMS2?request=getcapabilities

**Comment by tlvu** [comment]
> This error is not due to inaccessible. It is indicating that `request` query parameter is missing.
> Following works while unauthenticated:
> https://hirondelle.crim.ca/twitcher/ows/proxy/ncWMS2?request=getcapabilities

Oh this is odd, I can curl the "internal" url fine without any request param.  But you got a point here.  This might not be a real bug after all.

```
$ curl --include --silent http://pavics.ouranos.ca:8080/ncWMS2/ | head -20
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Cache-Control: no-cache
Pragma: no-cache
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-Length: 1329
Date: Mon, 27 Sep 2021 02:08:36 GMT

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<link rel=StyleSheet href="css/ncWMS.css" type="text/css" />
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Birdhouse ncWMS2 Server</title>
    </head>
    <body>

    <h1>Birdhouse ncWMS2 Server</h1>
    <h3>Running ncWMS v2.0.4</h3>
```

**Comment by fmigneault** [comment]
@tlvu 
It is partly due to `Magpie`. It is specified in the service definition that `request` is an "expected" parameter needed in order to determine which permission applies for the request. Since it is not provided, Magpie is not able to figure out if you should be allowed access or not. The service could be updated to use `GetCapabilities` by default if `request` is omitted, since it seems to allow it.

**Comment by tlvu** [comment]
> Error for the canarie monitoring:
> 
> ```
> [2021-09-24 20:49:01 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:1548)
> [2021-09-24 20:49:01,632] [1548] [ERROR] app_object : Exception occurs while trying to check status of node.ncWMS2-public
> [2021-09-24 20:49:01,632] ERROR in monitoring: Exception occurs while trying to check status of node.ncWMS2-public
> [2021-09-24 20:49:01 +0000] [1548] [INFO] Worker exiting (pid: 1548)
> ```

The Canarie monitoring failure of `ncWMS2-public` above that prompted this issue was finally due to a dying DNS server after our power outage.  We removed that bad DNS server from the list and everything seems to be back to normal.

Sorry for the false positive.
