### ISSUE TITLE
Improve the users/groups initialisation script

### ISSUE THREAD

**Issue by dbyrns** [Ouranosinc/Magpie#47]
We should create automatically "service" users use by services to access magpie.
Exemple are the catalog who needs an access to crawl thredds or project-api which required access to get the projects available to a particular user.
I propose that an env file lists all required "service" users that would be read by magpie initialisation script and also used by the services requiring that type of access to avoid duplicate user/pw configuration.

On top of that, these users + the anononymous user and the default users and administrators groups should be made read-only and prevent any renaming, deletion or password update.  (relates #164)

**Comment by fmigneault** [comment]
Most operations can be done with file: 
https://github.com/Ouranosinc/Magpie/blob/master/config/permissions.cfg

Could add sub fields to `user` section such that they get created as wanted with full definition.
```
user:
  username: <name>
  password: <pwd> 
  groups: 
    - <grp1>
    - <grp2>
```
