### ISSUE TITLE
Remove "Current" User Route

### ISSUE THREAD

**Issue by fmigneault** [Ouranosinc/Magpie#51]
`current` is used to access the logged user (or `anonymous` otherwise)
`https://{bird}/magpie/users/current`

If a user was created with the same name, unexpected behavior could occur.

On the other hand, route `https://{bird}/magpie/session` provides the exact same functionality without the special `current` user. If no session is active (no user logged in) no user info is returned with `"authenticated": false`.

The `current` user route should simply be removed.

This will affect many Twitcher routes... example: 
```
https://colibri.crim.ca/twitcher/ows/proxy/catalog/pywps?service=WPS&request=execute&version=1.0.0&identifier=pavicsearch&DataInputs=limit=10000;facets=*;type=Aggregate;distrib=true;constraints=project:ClimEx;
```

which seem to use `current` when proper permissions are obtained.

**Comment by dbyrns** [comment]
As decided in a meeting (june 7th AM, https://www.crim.ca/confluence/pages/viewpage.action?pageId=21761637) we decided to keep the route current.
