### ISSUE TITLE
Geoserver API

### ISSUE THREAD

**Issue by fmigneault** [Ouranosinc/Magpie#62]
# TODO: 

- permissions check accept requests ([Geoserver Requests](http://docs.geoserver.org/stable/en/user/rest/))
- permissions block other requests
- permissions read/write for resources ([Geoserver Workspaces](http://docs.geoserver.org/latest/en/api/#/1.0.0/workspaces.yaml))
- add to `service_type_dict` for reference

**Comment by dbyrns** [comment]
Will need to check permission on some of the route covered by this API : http://docs.geoserver.org/stable/en/user/rest/
By default remaining routes should be blocked.
@Zvax will tell what routes will be required.

Resources should be the workspaces? (http://docs.geoserver.org/latest/en/api/#/1.0.0/workspaces.yaml)
Permissions should be read / write.
Write access on the service allow workspace creation
Write access on a workspace allow shapefiles upload
Read access on the service allow all shapefiles to be retrieved
Read access on a particular workspace allow shapefiles of this workspace to be retrieved

**Comment by fmigneault** [comment]
resolved via PRs #69, Ouranosinc/PAVICS#88
