### ISSUE TITLE
Ensure inputs are trimmed (spaces, etc.)

### ISSUE THREAD

**Issue by fmigneault** [Ouranosinc/Magpie#84]
A service on hirondelle was named "ogctb13 " (notice the ending space).
This was causing errors when trying to edit the service via API and UI.

found via unittest run : 
http://ci.corpo.crim.ca:8081/view/PAVICS/job/PAVICS_magpie_test_hirondelle/41

Should refuse invalid inputs: 
- spaces
- slashes (/ \\)
- any other invalid characters that would break RESTful requests

**Comment by dbyrns** [comment]
+1 for the script!
I think that we can safely remove it... @tomLandry ?

**Comment by tomLandry** [comment]
Remove what, the ogctb13 provider? If so, yes. But expect other "ogc_testbed" providers in the future.

**Comment by dbyrns** [comment]
I'm totally fine with new providers from tb14. We will make sure to not add trailing spaces though.

**Comment by fmigneault** [comment]
ref #171

**Comment by ChaamC** [comment]
Other errors found :
- sending an empty input
- when editing an existing user, sending an info (username, email, ...) that is the same as the existing one ; in this case, it shouldn't produce an error, but accept the input anyway, without any change

**Comment by fmigneault** [comment]
@ChaamC 
For the empty input, what is the error? 
If it's a bad request, it is behaving as intended. The UI has very limited invalid operation error catching.
Could be added, but it becomes a bigger scope than current issue.

For the update, I believe that at least one change is expected on purpose in the UI, to ensure that an update is actually applied. The API will otherwise raise an error as a bad request (ie: asking something to be updated although nothing has to be updated).

**Comment by ChaamC** [comment]
@fmigneault 
I thought we might want to avoid displaying an error on another page (a blank page with some error info). For example, I think when you create a service with the same name as an existing one, it just displays an error message in red on the same page just beside the text box, instead of loading a new error page.
But, we can choose to leave it as it is, since it is still catching the error!

**Comment by fmigneault** [comment]
@ChaamC 
Yes, this is not critical to have it handled nicely in the UI for now. I think the returned error is conflict (409) which the expected behaviour. The blank page with error message is the way the API resolves the content-type (html) that is requested by the UI for the browser.
